title: Power BI Sales Dashboard
description: Interactive Business Intelligence Dashboard analyzing sales performance, profitability, and regional KPIs using Power BI.
theme: jekyll-theme-cayman

show_downloads: true

